#!/bin/bash
SCRIPT_NAME=$(basename "$0")
KUBE_HOME="${KUBE_HOME:=$HOME/.kube}"
KUBE_CONFIGS_DIR="${KUBE_CONFIGS_DIR:=$KUBE_HOME/configs}"

#
# list kubeconfig files
#
function list() {
    if [[ -d "$KUBE_CONFIGS_DIR" ]]; then
        echo 'available kubeconfig files:'
        echo "$KUBE_CONFIGS_DIR"
        pushd "$KUBE_CONFIGS_DIR" > /dev/null
        ls -l
        popd > /dev/null
        echo
    fi
    if [[ -d "$KUBE_HOME" ]]; then
        echo 'current kubeconfig file:'
        echo "$KUBE_HOME"
        pushd "$KUBE_HOME" > /dev/null
        ls -l config
        popd > /dev/null
    fi
}

#
# select a kubeconfig
#
function selectconfig() {
    selectconfig_parse_opts "$@"
    [[ ! -f "$KUBE_CONFIGS_DIR/$KUBE_CONFIG" ]] && echo "[ERROR] kubeconfig not found: $KUBE_CONFIGS_DIR/$KUBE_CONFIG" && exit 1
    cp "$KUBE_CONFIGS_DIR/$KUBE_CONFIG" "$KUBE_HOME/config"
}

function selectconfig_parse_opts() {
    if [[ $# = 0 ]]; then
        selectconfig_help
    fi
    if [[ "$1" = '-h' ]]; then
        selectconfig_help
    fi
    KUBE_CONFIG="$1"
}

function selectconfig_help() {
    local command='select'
    printf 'Usage: %s %s <kubeconfig> [-h]\n' "$SCRIPT_NAME" $command
    printf '\t%s\n' '-h: Prints help'
    exit 0
}

#
# exec k9s in a given context
#
function exec_k9s() {
    exec_k9s_parse_opts "$@"
    [[ ! -f "$KUBE_CONFIGS_DIR/$KUBE_CONFIG" ]] && echo "[ERROR] kubeconfig not found: $KUBE_CONFIGS_DIR/$KUBE_CONFIG" && exit 1
    k9s --kubeconfig "$KUBE_CONFIGS_DIR/$KUBE_CONFIG"
}

function exec_k9s_parse_opts() {
    if [[ $# = 0 ]]; then
        use_exec_k9s
    fi
    if [[ "$1" = '-h' ]]; then
        use_exec_k9s
    fi
    KUBE_CONFIG="$1"
}

function use_exec_k9s() {
    local command='k9s'
    printf 'Usage: %s %s <context> [-h]\n' "$SCRIPT_NAME" $command
    printf '\t%s\n' '-h: Prints help'
    exit 0
}

#
# spawn a subshell with a given kubeconfig
#
function exec_shell() {
    exec_shell_parse_opts "$@"
    [[ ! -f "$KUBE_CONFIGS_DIR/$KUBE_CONFIG" ]] && echo "[ERROR] kubeconfig not found: $KUBE_CONFIGS_DIR/$KUBE_CONFIG" && exit 1
    KUBECONFIG="$KUBE_CONFIGS_DIR/$KUBE_CONFIG" $SHELL
}

function exec_shell_parse_opts() {
    if [[ $# = 0 ]]; then
        exec_shell_help
    fi
    if [[ "$1" = '-h' ]]; then
        exec_shell_help
    fi
    KUBE_CONFIG="$1"
}

function exec_shell_help() {
    local command='shell'
    printf 'Usage: %s %s <kubeconfig> [-h]\n' "$SCRIPT_NAME" $command
    printf '\t%s\n' '-h: Prints help'
    exit 0
}

#
# print the current kubeconfig path
#
function print_config_path() {
    local path
    if [[ -n "$KUBECONFIG" ]]; then
        path="$KUBECONFIG"
    elif [[ -f "$KUBE_HOME/config" ]]; then
        path="$KUBE_HOME/config"
    else
        path='[none]'
    fi
    printf '\033[1;97m%s\033[0m\n' "$path"
}

#
# print the current kubeconfig contents
#
function print_config() {
    local path
    if [[ -n "$KUBECONFIG" ]]; then
        path="$KUBECONFIG"
    elif [[ -f "$KUBE_HOME/config" ]]; then
        path="$KUBE_HOME/config"
    else
        path='[none]'
    fi
    if [[ "$path" == '[none]' ]]; then
        echo '[none]'
    else
        cat "$path"
    fi
}

#
# print the current kubeconfig path and contents
#
function print_config_all() {
    echo "Shell Level: $SHLVL"
    echo ---
    local path
    if [[ -n "$KUBECONFIG" ]]; then
        path="$KUBECONFIG"
    elif [[ -f "$KUBE_HOME/config" ]]; then
        path="$KUBE_HOME/config"
    else
        path='[none]'
    fi
    printf '\033[1;97m%s\033[0m\n' "$path"
    if [[ "$path" != '[none]' ]]; then
        echo ---
        cat "$path"
    fi
}

#
# copy current ~/.kube/config to ~/.kube/configs/<name>
#
function copyconfig() {
    [[ $# = 0 ]] && echo "Usage: $SCRIPT_NAME cp <name>" && exit 1
    mkdir -p "$KUBE_CONFIGS_DIR"
    cp "$KUBE_HOME/config" "$KUBE_CONFIGS_DIR/$1"
    echo "copied $KUBE_HOME/config -> $KUBE_CONFIGS_DIR/$1"
}

#
# remove kubeconfig file
#
function remove() {
    remove_parse_opts "$@"
    rm "$KUBE_CONFIGS_DIR/$KUBE_CONFIG"
}

function remove_parse_opts() {
    if [[ $# = 0 ]]; then
        remove_help
    fi
    if [[ "$1" = '-h' ]]; then
        remove_help
    fi
    KUBE_CONFIG="$1"
}

function remove_help() {
    local command='remove'
    printf 'Usage: %s %s <kubeconfig> [-h]\n' "$SCRIPT_NAME" $command
    printf '\t%s\n' '-h: Prints help'
    exit 0
}

function parse_command_line() {
    if [[ $# -eq 0 ]]; then
        help
    fi
    case "$1" in
        -h|--help)
            help
            ;;
        -h*)
            help
            ;;
        list|ls)
            list
            ;;
        select|s)
            shift
            selectconfig "$@"
            ;;
        k9s|9)
            shift
            exec_k9s "$@"
            ;;
        remove|rm)
            shift
            remove "$@"
            ;;
        shell|sh)
            shift
            exec_shell "$@"
            ;;
        cp|copy)
            shift
            copyconfig "$@"
            ;;
        print|p)
            print_config
            ;;
        printpath|pp)
            print_config_path
            ;;
        printall|pa)
            print_config_all
            ;;
        *)
            help
            ;;
    esac
}

function help() {
    printf 'Usage: %s <command> [-h]\n' "$SCRIPT_NAME"
    echo 'commands:'
    echo 'ls|list: list kubeconfig files'
    echo 's|select <kubeconfig>: select a kubeconfig file'
    echo '9|k9s <context>: exec k9s with the context of a kubeconfig file'
    echo 'sh|shell <kubeconfig>: spawn a subshell with the kubeconfig isolated to this session'
    echo 'p|print: print the current kubeconfig contents'
    echo 'pp|printpath: print the current kubeconfig path'
    echo 'pa|printall: print the current kubeconfig path and contents'
    echo 'cp|copy <name>: copy current kubeconfig to configs/<name>'
    echo 'rm|remove <kubeconfig>: remove kubeconfig file'
    echo '-h: prints help'
    exit 0
}

parse_command_line "$@"
